import { db } from "@workspace/db";
import { usersTable, roomsTable, interactionsTable } from "@workspace/db";
import bcrypt from "bcryptjs";

async function seed() {
  console.log("Seeding database...");

  const defaultHash = await bcrypt.hash("password123", 10);

  const users = await db.insert(usersTable).values([
    {
      firstName: "Guest",
      lastName: "Visitor",
      email: "guest@ghar-khoj.local",
      phone: "",
      role: "tenant",
      isVerified: false,
      verificationStatus: "pending",
      preferredCity: "Kathmandu",
      bio: "Browse rooms and chat with owners without signing in.",
      passwordHash: defaultHash,
    },
    {
      firstName: "Sita",
      lastName: "Thapa",
      email: "sita.thapa@example.com",
      phone: "9851234567",
      role: "owner",
      isVerified: true,
      verificationStatus: "approved",
      preferredCity: "Lalitpur",
      passwordHash: defaultHash,
    },
    {
      firstName: "Bikash",
      lastName: "Rai",
      email: "bikash.rai@example.com",
      phone: "9861234567",
      role: "owner",
      isVerified: true,
      verificationStatus: "approved",
      preferredCity: "Pokhara",
      passwordHash: defaultHash,
    },
    {
      firstName: "Priya",
      lastName: "Gurung",
      email: "priya.gurung@example.com",
      phone: "9841111222",
      role: "tenant",
      isVerified: false,
      verificationStatus: "pending",
      preferredCity: "Kathmandu",
      passwordHash: defaultHash,
    },
    {
      firstName: "Suresh",
      lastName: "Adhikari",
      email: "suresh.adhikari@example.com",
      phone: "9851111333",
      role: "admin",
      isVerified: true,
      verificationStatus: "approved",
      preferredCity: "Kathmandu",
      passwordHash: defaultHash,
    },
  ]).returning();

  console.log(`Seeded ${users.length} users`);

  const rooms = await db.insert(roomsTable).values([
    {
      ownerId: users[1].id,
      title: "Single Room for Rent – Baneshwor",
      description: "Clean and comfortable single room on 2nd floor. Attached bathroom with hot water. Regular water supply from boring. Ideal for working professionals. Walking distance to Baneshwor Chowk.",
      price: 8500,
      roomType: "single",
      tenantType: "any",
      city: "Kathmandu",
      address: "Baneshwor, Kathmandu",
      latitude: 27.6933,
      longitude: 85.3394,
      parking: false,
      amenities: ["WiFi", "Hot Water", "24/7 Water", "Electricity", "Kitchen"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Baneshwor Chowk 🚌 (3 min)", "Dillibazar Hospital 🏥", "Baneshwor School 🏫"],
    },
    {
      ownerId: users[1].id,
      title: "2BHK Flat – Lazimpat",
      description: "Spacious fully-furnished 2BHK flat with city-view balcony on 4th floor. Lift available. Perfect for families or professional couples. Near embassy area and BICC.",
      price: 26000,
      roomType: "flat",
      tenantType: "family",
      city: "Kathmandu",
      address: "Lazimpat, Kathmandu",
      latitude: 27.7219,
      longitude: 85.3197,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Balcony", "Furnished", "TV", "AC", "Lift", "Parking"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Lazimpat Bus Stop 🚌", "BICC 🏛️", "Bir Hospital 🏥"],
    },
    {
      ownerId: users[1].id,
      title: "1BHK Flat for Rent – Koteshwor",
      description: "Well-maintained 1BHK flat on 2nd floor with natural light. Separate kitchen, attached bathroom. 24/7 water supply from boring. Near main road and market.",
      price: 16000,
      roomType: "flat",
      tenantType: "any",
      city: "Kathmandu",
      address: "Koteshwor, Kathmandu",
      latitude: 27.6842,
      longitude: 85.3555,
      parking: true,
      amenities: ["WiFi", "24/7 Water", "Electricity", "Kitchen", "Attached Bathroom", "Parking"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Koteshwor Chowk 🚌 (500m)", "City Hospital 🏥", "Koteshwor Market 🛒"],
    },
    {
      ownerId: users[1].id,
      title: "Furnished Studio – Naxal",
      description: "Fully furnished studio apartment on 3rd floor of new building. Includes bed, wardrobe, TV, gas stove. Quiet residential area. Lift available.",
      price: 18500,
      roomType: "studio",
      tenantType: "professional",
      city: "Kathmandu",
      address: "Naxal, Kathmandu",
      latitude: 27.7157,
      longitude: 85.3278,
      parking: false,
      amenities: ["WiFi", "Water", "Electricity", "Furnished", "TV", "Gas", "Lift"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Naxal Bhagwati Temple 🛕", "NIC Asia Bank 🏦", "Naxal Bus Stop 🚌"],
    },
    {
      ownerId: users[1].id,
      title: "Single Room with Balcony – Baluwatar",
      description: "Well-lit single room near Baluwatar Garden with private attached bathroom. Regular water supply. 10 min to Lazimpat. Suitable for NGO or embassy professionals.",
      price: 10000,
      roomType: "single",
      tenantType: "professional",
      city: "Kathmandu",
      address: "Baluwatar, Kathmandu",
      latitude: 27.7244,
      longitude: 85.3292,
      parking: false,
      amenities: ["WiFi", "Attached Bathroom", "Water", "Electricity", "Hot Water"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Baluwatar Garden 🌿", "Ring Road Bus Stop 🚌", "Blue Cross Hospital 🏥"],
    },
    {
      ownerId: users[1].id,
      title: "Double Room – Maharajgunj",
      description: "Bright double room on 3rd floor with private balcony. Shared bathroom with one tenant only. Mountain views on clear days. Walking distance to embassies.",
      price: 13000,
      roomType: "double",
      tenantType: "any",
      city: "Kathmandu",
      address: "Maharajgunj, Kathmandu",
      latitude: 27.7345,
      longitude: 85.3253,
      parking: false,
      amenities: ["WiFi", "Water", "Electricity", "Balcony", "Hot Water"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Teaching Hospital 🏥", "BICC Convention Center 🏛️", "Maharajgunj Bus Stop 🚌"],
    },
    {
      ownerId: users[2].id,
      title: "Studio Apartment – Lakeside Pokhara",
      description: "Peaceful studio with Phewa Lake view from balcony. Fully furnished. Near Barahi Temple and Lakeside market. 24hr security. Perfect for couples or solo professionals.",
      price: 14000,
      roomType: "studio",
      tenantType: "any",
      city: "Pokhara",
      address: "Lakeside Ward-6, Pokhara",
      latitude: 28.2096,
      longitude: 83.9556,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Balcony", "Hot Water", "Furnished"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Phewa Lake Barahi Ghat 🛕", "Fishtail Lodge 🏨", "Lakeside Market 🛒"],
    },
    {
      ownerId: users[2].id,
      title: "Modern 2BHK – Lakeside Pokhara",
      description: "Beautiful 2BHK flat with panoramic lake view. Fully furnished, two bedrooms, living room. Parking available. Walking distance to Phewa Lake. Ideal for family.",
      price: 22000,
      roomType: "flat",
      tenantType: "family",
      city: "Pokhara",
      address: "Lakeside, Pokhara",
      latitude: 28.2107,
      longitude: 83.9560,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Furnished", "Balcony", "Parking", "Hot Water", "TV"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Phewa Lake 🛕", "Western Regional Hospital 🏥", "Lakeside Bus Stop 🚌"],
    },
    {
      ownerId: users[4].id,
      title: "Budget Room – Durbar Square Area, Bhaktapur",
      description: "Budget-friendly single room in historic Bhaktapur. Close to Durbar Square and pottery market. Basic amenities. Ideal for students or heritage enthusiasts.",
      price: 6000,
      roomType: "single",
      tenantType: "student",
      city: "Bhaktapur",
      address: "Durbar Square Area, Bhaktapur",
      latitude: 27.6722,
      longitude: 85.4298,
      parking: false,
      amenities: ["Water", "Electricity"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Bhaktapur Durbar Square 🛕", "Pottery Square 🏺", "Bhaktapur Bus Stop 🚌"],
    },
    {
      ownerId: users[4].id,
      title: "2BHK Flat – Jawalakhel, Lalitpur",
      description: "Spacious 2BHK flat with balcony on 1st floor. Two bedrooms, living room, modern kitchen. Parking for one vehicle. Near Patan Hospital. Ideal for family.",
      price: 28000,
      roomType: "flat",
      tenantType: "family",
      city: "Lalitpur",
      address: "Jawalakhel, Lalitpur",
      latitude: 27.6723,
      longitude: 85.3163,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Balcony", "Parking", "AC"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Jawalakhel Bus Stop 🚌", "Patan Hospital 🏥", "Jawalakhel Zoo 🦁"],
    },
    {
      ownerId: users[1].id,
      title: "Shared Room for Students – Kirtipur",
      description: "Two-sharing room for students near TU campus. Common kitchen and bathroom. All utilities included. 10 min walk to TU main gate. Very affordable.",
      price: 4000,
      roomType: "shared",
      tenantType: "student",
      city: "Kathmandu",
      address: "Kirtipur, Kathmandu",
      latitude: 27.6797,
      longitude: 85.2787,
      parking: false,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: false,
      isAvailable: true,
      nearbyLandmarks: ["TU Campus 🏫", "Kirtipur Bus Stop 🚌", "Kirtipur Hospital 🏥"],
    },
    {
      ownerId: users[2].id,
      title: "Double Room – Patan, Lalitpur",
      description: "Spacious double room in the cultural heart of Lalitpur. Walking distance to Patan Durbar Square and Mangalbazar. Furnished with wardrobe and study table.",
      price: 11000,
      roomType: "double",
      tenantType: "professional",
      city: "Lalitpur",
      address: "Patan, Lalitpur",
      latitude: 27.6641,
      longitude: 85.3240,
      parking: false,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Furnished"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Patan Durbar Square 🛕", "Patan Hospital 🏥", "Lagankhel Bus Stop 🚌"],
    },
    {
      ownerId: users[4].id,
      title: "Female-Only Studio – Thamel",
      description: "Safe and secure studio for female tenants only. Located in the tourist hub of Thamel with easy access to restaurants and transportation. CCTV in common areas.",
      price: 15000,
      roomType: "studio",
      tenantType: "female",
      city: "Kathmandu",
      address: "Thamel, Kathmandu",
      latitude: 27.7152,
      longitude: 85.3122,
      parking: false,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Furnished", "TV", "CCTV"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Thamel Bus Stop 🚌", "Teaching Hospital 🏥", "Swayambhunath 🛕"],
    },
    {
      ownerId: users[4].id,
      title: "Affordable Single – Kalanki",
      description: "Clean single room with common bathroom. Water from boring. Regular electricity. Kitchen access available. On quiet lane, 5 min walk to Kalanki Chowk.",
      price: 6500,
      roomType: "single",
      tenantType: "male",
      city: "Kathmandu",
      address: "Kalanki, Kathmandu",
      latitude: 27.6938,
      longitude: 85.2802,
      parking: false,
      amenities: ["Water", "Electricity", "Kitchen Access"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Kalanki Chowk 🚌", "Mathura Hospital 🏥", "Big Mart 🛒"],
    },
    {
      ownerId: users[4].id,
      title: "Double Room Near Pokhara Airport",
      description: "Well-maintained double room close to Pokhara Airport. Good for professionals working at the airport or frequent flyers. Quiet residential area with parking.",
      price: 9000,
      roomType: "double",
      tenantType: "any",
      city: "Pokhara",
      address: "Airport Road, Pokhara",
      latitude: 28.1990,
      longitude: 83.9736,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Parking"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["Pokhara Airport 🛫", "Western Regional Hospital 🏥", "Airport Chowk 🚌"],
    },
    {
      ownerId: users[4].id,
      title: "Premium 3BHK Luxury Flat – New Baneshwor",
      description: "Premium 3BHK apartment on 6th floor with panoramic city view. Modern amenities including generator backup, CCTV, 24/7 security guard. Fully furnished.",
      price: 45000,
      roomType: "flat",
      tenantType: "family",
      city: "Kathmandu",
      address: "New Baneshwor, Kathmandu",
      latitude: 27.6966,
      longitude: 85.3427,
      parking: true,
      amenities: ["WiFi", "Water", "Electricity", "Kitchen", "Balcony", "Furnished", "TV", "AC", "Generator", "CCTV", "Lift"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: true,
      isAvailable: true,
      nearbyLandmarks: ["New Baneshwor Bus Stop 🚌", "CIWEC Hospital 🏥", "Shangrila Mall 🛒"],
    },
    {
      ownerId: users[2].id,
      title: "Single Room – Biratnagar Industrial Area",
      description: "Clean single room for working-class individuals near industrial area. Near factories and offices. Basic amenities. Affordable monthly rent.",
      price: 5000,
      roomType: "single",
      tenantType: "male",
      city: "Biratnagar",
      address: "Industrial Area, Biratnagar",
      latitude: 26.4525,
      longitude: 87.2718,
      parking: false,
      amenities: ["Water", "Electricity"],
      photos: ["/images/hero-kathmandu.png"],
      isVerified: false,
      isAvailable: true,
      nearbyLandmarks: ["Industrial Bus Stop 🚌", "Koshi Zonal Hospital 🏥"],
    },
  ]).returning();

  console.log(`Seeded ${rooms.length} rooms`);

  await db.insert(interactionsTable).values([
    { userId: users[0].id, roomId: rooms[0].id, type: "view" },
    { userId: users[0].id, roomId: rooms[1].id, type: "view" },
    { userId: users[0].id, roomId: rooms[0].id, type: "save" },
    { userId: users[0].id, roomId: rooms[5].id, type: "view" },
    { userId: users[3].id, roomId: rooms[6].id, type: "view" },
    { userId: users[3].id, roomId: rooms[6].id, type: "save" },
    { userId: users[3].id, roomId: rooms[11].id, type: "view" },
  ]);

  console.log("Seeded interactions");
  console.log("Done! Database seeded successfully.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
